namespace be_asa_shared_localization.Enums.ModuleAuthen.Customer
{
    public enum CustomerKeys
    {
        BRANCH_SETTING_VALUE_REQUIRED,
        BRANCH_SETTING_INVALID_BOOL,
        BRANCH_SETTING_INVALID_INT,
        BRANCH_SETTING_INVALID_LONG,
        BRANCH_SETTING_INVALID_DECIMAL,
        BRANCH_SETTING_INVALID_DATETIME,
        BRANCH_SETTING_INVALID_ALLOWED,

        EMAIL_CONFIRM_SUCCESS,
        EMAIL_CONFIRM_FAILED,
        EMAIL_TEMPLATE_NOT_FOUND,
        EMAIL_CONFIG_NOT_FOUND,
        INVALID_CONFIRM_TOKEN,
        USER_NOT_FOUND,
        USER_ALREADY_ACTIVATED
    }
}
