namespace be_asa_shared_localization.Enums.PermissionGroup
{
    public enum PermissionGroupKeys
    {
        TYPE_NOT_FOUND,
        NAME_EXISTS,
        NOT_FOUND,
        DELETE_ACCESS_DENIED,

        CREATE_ADMIN_GROUP_NO_PERMISSION,
        CREATE_CONTAINS_ADMIN_FUNCTION_NO_PERMISSION,
        CREATE_ADMIN_GROUP_REQUIRE_ADMIN_FUNCTIONS,
        CREATE_ADMIN_FUNCTIONS_REQUIRE_ADMIN_GROUP,

        UPDATE_GROUP_NO_PERMISSION,
        UPDATE_ADMIN_GROUP_NO_PERMISSION,
        UPDATE_ADMIN_GROUP_REQUIRE_ADMIN_FUNCTIONS,
        UPDATE_ADMIN_FUNCTIONS_REQUIRE_ADMIN_GROUP
    }
}
