namespace be_asa_shared_localization.Enums.Email
{
    public enum EmailKeys
    {
        EMAIL_CONFIG_NOT_FOUND,
        EMAIL_TEMPLATE_NOT_FOUND,
        EMAIL_SEND_SUCCESS,
        EMAIL_SEND_FAILED,
        EMAIL_SAVE_LOG_FAILED,
        EMAIL_REQUIRED,
        EMAIL_INVALID,
        EMAIL_CONFIG_ALREADY_EXISTS,
        CANNOT_DELETE_DEFAULT_EMAIL_CONFIG,

        TEMPLATE_NOT_FOUND,
        TEMPLATE_ALREADY_EXISTS,
        TEMPLATE_GROUP_NOT_FOUND,
        PLACEHOLDER_MISSING_IN_TEMPLATE,
        PLACEHOLDER_DUPLICATED,
        PLACEHOLDER_INVALID,
        PLACEHOLDER_NOT_FOUND
    }
}
