namespace be_asa_shared_localization.Enums.Common
{
    public enum CommonKeys
    {
        DATA_LOADED_SUCCESSFULLY,
        DATA_LOADED_FAILED,
        DATA_EXPORT_SUCCESSFULLY,
        DATA_EXPORT_FAILED,
        DATA_CREATED,
        DATA_UPDATED,
        DATA_DELETED,
        UNHANDLED_ERROR,
        NAME_CAN_NOT_EMPTY,
        LOG_NOT_FOUND,


        // Dashboard
        USER_NOT_FOUND_OR_INACTIVE,
        WIDGET_NOT_FOUND,
        DASHBOARD_NOT_FOUND,
        USER_WIDGET_NOT_FOUND,
        WIDGET_POSITION_ALREADY_EXISTS,
        DUPLICATE_WIDGET_POSITION,
        INVALID_WIDGETS_IN_DASHBOARD,
        REQUIRED_FIELD_MISSING,
        INVALID_FIELD_FORMAT,
        INVALID_DATE_FORMAT,
        METRIC_EXECUTION_ERROR

    }
}
